{% set name = "docker-manager" %}
{% set data = load_setup_py_data() %}



package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - {{ name|lower }}

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}