{% set name = "docker-manager" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - {{ name|lower }}

about:
  home: https://github.com/hummingbot/docker-manager
  license: Apache 2.0
summary: "This repository provides a set of functionalities for managing Docker containers in the context of the specified use case."