name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
        python-version: 3.11
        auto-update-conda: true
        activate-environment: ANACONDA
        use-only-tar-bz2: true

    - name: Verify conda environment
      run: |
        conda info | grep "user-agent"

    - name: Install Anaconda
      run: |
        conda install -y anaconda-client

    - name: Build conda package
      run: |
        cd .conda
        conda build --output-folder . .
    
    - name: Convert binaries to other platforms
      run: |
        platforms=( osx-64 win-64 )
        find ./linux-64/ -name *.tar.bz2 | while read file
        do
            echo $file
            for platform in "${platforms[@]}"
            do
              conda convert --platform $platform $file  -o .
            done    
        done

    - name: Upload package
      run: |
        find . -name *.tar.bz2 | while read file
        do
            echo $file
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $file
        done
